/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ValidatorFn } from "./global/errorHandler";
export namespace Components {
    interface UiwInputNumber {
        "disabled": boolean;
        "error": string;
        "hint": string;
        "label": string;
        "max": number;
        "min": number;
        "name": string;
        "optionalLabel": string;
        "placeholder": string;
        "required": boolean;
        "step": number;
        "translations"?: {
      buttonIncreaseTitle?: string
      buttonDecreaseTitle?: string
      required?: string
      max?: string
      min?: string
  };
        "validators": ValidatorFn[];
        "value"?: number;
    }
}
declare global {
    interface HTMLUiwInputNumberElement extends Components.UiwInputNumber, HTMLStencilElement {
    }
    var HTMLUiwInputNumberElement: {
        prototype: HTMLUiwInputNumberElement;
        new (): HTMLUiwInputNumberElement;
    };
    interface HTMLElementTagNameMap {
        "uiw-input-number": HTMLUiwInputNumberElement;
    }
}
declare namespace LocalJSX {
    interface UiwInputNumber {
        "disabled"?: boolean;
        "error"?: string;
        "hint"?: string;
        "label"?: string;
        "max"?: number;
        "min"?: number;
        "name"?: string;
        "onNwccInputNumberChange"?: (event: CustomEvent<number>) => void;
        "onNwccInputNumberDecreaseClick"?: (event: CustomEvent<number>) => void;
        "onNwccInputNumberIncreaseClick"?: (event: CustomEvent<number>) => void;
        "onNwccInputNumberInputBlur"?: (event: CustomEvent<FocusEvent>) => void;
        "onNwccInputNumberInputChange"?: (event: CustomEvent<number>) => void;
        "onNwccInputNumberInputFocus"?: (event: CustomEvent<FocusEvent>) => void;
        "optionalLabel"?: string;
        "placeholder"?: string;
        "required"?: boolean;
        "step"?: number;
        "translations"?: {
      buttonIncreaseTitle?: string
      buttonDecreaseTitle?: string
      required?: string
      max?: string
      min?: string
  };
        "validators"?: ValidatorFn[];
        "value"?: number;
    }
    interface IntrinsicElements {
        "uiw-input-number": UiwInputNumber;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "uiw-input-number": LocalJSX.UiwInputNumber & JSXBase.HTMLAttributes<HTMLUiwInputNumberElement>;
        }
    }
}
